---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
stringData:
  my-secret-data: thisisasecretvalue
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: mlops-demo-datascience
data:
  my-configmap-data: thisisaconfigmapvalue
